// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaVGy_J11xaFxN-ssOuIE0w7YFdVTqlbk',
    appId: '1:325705345982:web:2eed8dadfcc13ffbd7e7ef',
    messagingSenderId: '325705345982',
    projectId: 'connectkasa-84f23',
    authDomain: 'connectkasa-84f23.firebaseapp.com',
    storageBucket: 'connectkasa-84f23.appspot.com',
    measurementId: 'G-ZW0HG41FVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUm-fFBYmMzKBYub-50EMBXPdKW0G-fLc',
    appId: '1:325705345982:android:731cd0e4e917d361d7e7ef',
    messagingSenderId: '325705345982',
    projectId: 'connectkasa-84f23',
    storageBucket: 'connectkasa-84f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGodmYAmRU5y5_d0erkvmjNATA-Yg1JY8',
    appId: '1:325705345982:ios:8bc16879122f9076d7e7ef',
    messagingSenderId: '325705345982',
    projectId: 'connectkasa-84f23',
    storageBucket: 'connectkasa-84f23.appspot.com',
    iosBundleId: 'fr.connectkasa.connectKasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGodmYAmRU5y5_d0erkvmjNATA-Yg1JY8',
    appId: '1:325705345982:ios:7c722a7eaf3543e6d7e7ef',
    messagingSenderId: '325705345982',
    projectId: 'connectkasa-84f23',
    storageBucket: 'connectkasa-84f23.appspot.com',
    iosBundleId: 'fr.connectkasa.connectKasa.RunnerTests',
  );
}
