// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOc2vgxw1BnxjdAUy4WTrNbpLfCd-v0_k',
    appId: '1:814247048228:web:796f0924df9c5ffccd94b1',
    messagingSenderId: '814247048228',
    projectId: 'konodal-dev',
    authDomain: 'konodal-dev.firebaseapp.com',
    storageBucket: 'konodal-dev.firebasestorage.app',
    measurementId: 'G-VRLLE300R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdWUq_o685acDxUbppMVVPZr2wQJwT4q8',
    appId: '1:814247048228:android:be239b9015268993cd94b1',
    messagingSenderId: '814247048228',
    projectId: 'konodal-dev',
    storageBucket: 'konodal-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPcPqDlkgqOXxTQqFyfyuj8zlEDszOCE',
    appId: '1:814247048228:ios:55cf43dc725f3f77cd94b1',
    messagingSenderId: '814247048228',
    projectId: 'konodal-dev',
    storageBucket: 'konodal-dev.firebasestorage.app',
    iosBundleId: 'com.konodal.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPcPqDlkgqOXxTQqFyfyuj8zlEDszOCE',
    appId: '1:814247048228:ios:55cf43dc725f3f77cd94b1',
    messagingSenderId: '814247048228',
    projectId: 'konodal-dev',
    storageBucket: 'konodal-dev.firebasestorage.app',
    iosBundleId: 'com.konodal.app',
  );
}
